name: Publish to NPM

on:
  push:
    branches:
      - main
      - master

jobs:
  publish_npm:
    permissions:
      id-token: write
      contents: read
    uses: pgnqukezrdxmhjso/koishi-plugin-rzgtboeyndxsklmq-commons/.github/workflows/publish_npm.yml@473dcd3fe09508e237db987801c2767b70dd9e7f
